### ISSUE TITLE
Need to optimizing QoS's isPPGGoodQuality method?

### ISSUE THREAD

**Issue by Nebu1eto** [derekmerck/PERSEUS#5]
Hello, thanks for nice Intellivue's export protocol client and project.

I'm running in our testbed, and It works well but it too much use CPU. So I profiled with Pycharm's profiler. `QualityOfSignal.isPPGGoodQuality` method uses many numpy and scipy's calculating functions and it makes slower.

I turn off it(just annotate this part.), and process's CPU usage is certainly decreased.
How about refactoring and optimizing it to get more performance?

**Comment by derekmerck** [comment]
Glad to hear that you've had good luck getting it to work!  Agree that the QoS takes too much computation power, and we should only be computing it once every few seconds anyway.  Your approach of just turning it off is probably best (you should be able to just comment out the post-processing functions that get attached to the data stream in `main()`), since it's a secondary analysis rather than primary data anyway.  I asked our colleagues at UCSF to refactor it previously and I'm waiting to hear back from them.
